# Generated by Django 2.2.4 on 2019-10-31 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='dias',
        ),
        migrations.AddField(
            model_name='turma',
            name='dias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Dia'),
        ),
        migrations.DeleteModel(
            name='DiaEmTurma',
        ),
    ]
