# Generated by Django 2.2.4 on 2019-10-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='grupo',
            field=models.ManyToManyField(blank=True, through='web.GrupoEmTurma', to='web.Grupo'),
        ),
    ]
